### ISSUE TITLE
a trouble

### ISSUE THREAD

**Issue by tuoxiaozhong** [bay6/prerequisite#47]
How can I know if I had pull request successfully?

**Comment by tuoxiaozhong** [comment]
assigned

**Comment by hlee** [comment]
https://github.com/tuoxiaozhong/prerequisite/commits/master

If you saw your commit in the master commits history, then that meas your PR has been accepted.

**Comment by hlee** [comment]
https://github.com/bay6/prerequisite/pull/43

We have not accepted it, because there is conflit. And that conflict may caused by your windows environment.

**Comment by hlee** [comment]
![screen shot 2013-07-14 at 4 15 04 pm](https://f.cloud.github.com/assets/83296/794849/1cdb1b72-ecc2-11e2-8c0e-c283217ed27c.png)
